config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new , :create , :edit , :update]
  resources :microposts,          only: [:create, :destroy]
  resources :ads,                 only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :blogs
  resources :certificates
  resources :faqs
end

app/models/faq.rb
class Faq < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
    before_action :super_user, only: [:edit, :update]
    before_action :admin_user, only: [:edit, :update, :create, :new, :destroy]

    def index
        @faqs = Faq.paginate(page: params[:page])
    end

    def new
        @faq = Faq.new
    end

    def update
        if @faq.update_attributes(faq_params)
            flash[:success] = 'FAQ updated!'
            redirect_to faqs_path
        else
            render 'edit'
        end
    end

    def show
    end

    def create
        @faq = current_user.faqs.build(faq_params)
        if @faq.save
            flash[:success] = 'FAQ created!'
            redirect_to faqs_path
        else
            render 'new'
        end
    end

    def destroy
        Faq.find(params[:id]).destroy
        flash[:success] = 'FAQ deleted!'
        redirect_to request.referrer || root_url
    end

    private

    def faq_params
        params.require(:faq).permit(:content, :title, :subtitle, :picture)
    end

    def super_user
        @faq = Faq.find_by(id: params[:id])
        redirect_to faqs_path if @faq.nil?
    end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form_faq.html.erb
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h3 class="panel-title pull-left"><%= yield(:form_title) %></h3>
    </div>
    <div class="modal-body">
        <%= simple_form_for @faq do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
            <%= f.input :title, autofocus: true %>
        </div>
        <div class="form-group">
            <%= f.input :content, input_html: {rows: "5"} %>
        </div>
        <div class="form-group">
            <%= f.button :submit, class: "btn btn-primary" %>
        </div>
        <% end %>
    </div>
</div>

app/views/faqs/edit.html.erb
<% provide(:title, "FAQ") %>

<h1>Editing FAQ</h1>

<div class="row">
<%= render 'form_faq', faq: @faq %>
</div>

app/views/faqs/index.html.erb
<% provide(:title, "FAQ") %>
<h1>Frequently Asked Questions</h1>
<% if logged_in? %>
<% if current_user.admin? %>
<div class="text-center">
<%= link_to "Create FAQ", new_faq_path, class: "btn btn-primary" %>
</div>
<% end %>
<% end %>
<hr>
<% @faqs.each do |faq| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= faq.title %>
    <% if logged_in? %>
    <% if current_user.admin? && !current_user?(faq) %>
    <div class="pull-right">
    <%= link_to "Edit", edit_faq_path(faq) %>
    |
    <%= link_to "Delete", faq, method: :delete,
                            data: { confirm: "You sure?" } %>
    </div>
    <% end %>
    <% end %>
  </div>
  <div class="panel-body">
    <%= faq.content %>
  </div>
</div>
<% end %>

app/views/faqs/new.html.erb
<% provide(:title, "FAQ") %>
<% provide(:form_title, "New FAQ") %>
<h1>New FAQ</h1>

<%= render 'form_faq' %>