config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new , :create , :edit , :update]
  resources :microposts,          only: [:create, :destroy]
  resources :ads,                 only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :blogs
  resources :certificates
  resources :faqs
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  default_scope -> {order(created_at: :desc)}

  validates :blog_content,    presence: true
  validates :user_id,         presence: true
  validates :blog_title,      presence: true
  validates :blog_subtitle,   presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

    #before_action :logged_in_user,  only: [:create, :destroy, :new]
    before_action :super_user,      only: [:destroy, :edit, :update]
    before_action :set_blog,        only: [:show]
    before_action :admin_user,      only: [:destroy]

    def index
        @blogs = Blog.paginate(page: params[:page])
    end

    def new
        @blog = Blog.new
    end

    def create
        @blog = current_user.blogs.build(blog_params)
        if @blog.save
            flash[:success] = 'Blog post created!'
            redirect_to blogs_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @blog.update_attributes(blog_params)
            flash[:success] = 'Blog post updated!'
            render 'show'
        else
            render 'edit'
        end
    end

    def show
    end

    def destroy
        Blog.find(params[:id]).destroy
        flash[:success] = 'Blog post deleted!'
        redirect_to request.referrer || root_url
    end

    private

    def set_blog
        @blog = Blog.find(params[:id])
    end

    def blog_params
        params.require(:blog).permit(:blog_content, :blog_title, :blog_subtitle)
    end

    def super_user
        @blog = Blog.find_by(id: params[:id])
        redirect_to root_url if @blog.nil?
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h3 class="panel-title pull-left"><%= yield(:form_title) %></h3>
    </div>
    <div class="modal-body">

        <%= simple_form_for @blog do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

            <div class="form-group">
                <%= f.input :blog_title, label: "Title", placeholder: "Title", autofocus: true %>
            </div>

            <div class="form-group">
                <%= f.input :blog_subtitle, label: "Sub title", placeholder: "Sub title" %>
            </div>

            <div class="form-group">
                <%= f.input :blog_content, label: "Content", as: :ckeditor, input_html: {ckeditor: {toolbar: 'FULL'}} %>
            </div>

            <div class="form-group text-center">
                <%= f.button :submit, class: 'btn btn-primary' %>
                <p>
                    Need help on how to use the editor above? Click
                    <%= link_to "here", help_path %>
                </p>
            </div>
        <% end %>
    </div>
</div>

app/views/blogs/edit.html.erb
<% provide(:title, "Blogs") %>

<h1>Editing Article</h1>

<div class="row">
<%= render 'form', blog: @blog %>
</div>

app/views/blogs/index.html.erb
<% provide(:title, "Blogs") %>

<header class="intro-header" style="background-image:
    url('http://www.download-hd-wallpapers.com/wp-content/uploads/2014/08/dark-abstract-wallpaper2.jpg'">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Life in KIT</h1>
                    <hr class="small">
                    <span class="subheading">Lesson learnt worth to be shared</span>
                </div>
            </div>
        </div>
    </div>
</header>

<% if logged_in? %>
<div class="center">
    <%= link_to 'Share My Article', new_blog_path, class: "btn btn-primary" %>
</div>
<% end %>
<!-- Main Content -->
<div class="row">
    <div class="center">
        <%= will_paginate @blogs %>
    </div>
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <% @blogs.each do |blog| %>
        <hr>
        <div class="post-preview">
            <%= link_to blog do %>
            <h2 class="post-title">
                <%= blog.blog_title %>
            </h2>
            <h3 class="post-subtitle">
                <%= blog.blog_subtitle %>
            </h3>
            <% end %>

            <p class="post-meta">Posted by
                <%= link_to blog.user.name, blog.user %>
                <%= time_ago_in_words(blog.created_at) %>
                ago
                <% if logged_in? %>
                <% if current_user.admin? || current_user?(blog.user) %>
                <%= link_to 'Edit', edit_blog_path(blog) %>
                |
                <%= link_to "Delete", blog, method: :delete,
                                                 data: { confirm: "You sure?" } %>
                <% end %>
                <% end %>
            </p>
            <% if blog.blog_content.length > 300 %>
              <% trctcontent = blog.blog_content.truncate(300) %>
              <%= raw(trctcontent) %>
              <br>
              <%= link_to 'Read more', blog %>
            <% else %>
              <%= raw(blog.blog_content) %>
            <% end %>
        </div>

        <% end %>
        <div class="center">
            <%= will_paginate @blogs %>
        </div>
    </div>
</div>

app/views/blogs/new.html.erb
<% provide(:title, "Blogs") %>
<% provide(:form_title, "Create new blog post") %>

<h1>New Post</h1>

<div class="container-fluid">
    <%= render 'form' %>
</div>

app/views/blogs/show.html.erb
<h4 class="text-center">Press F11 to enter or exit full screen</h4>
<section id="full">
    <header class="intro-header" style="background-image:
    url('http://www.download-hd-wallpapers.com/wp-content/uploads/2014/08/dark-abstract-wallpaper2.jpg')">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-heading">
                    <h1><%= @blog.blog_title %></h1>
                    <h2 class="subheading"><%= @blog.blog_subtitle %></h2>
                    <span class="meta">Posted by
                        <%= link_to @blog.user.name, @blog.user %>
                        <%= time_ago_in_words(@blog.created_at) %>
                        ago</span>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <%= raw(@blog.blog_content) %>
                <br><br><br>
                <hr>
                <div class="button-group text-center">
                <% if current_user?(@blog.user) %>
                <%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-primary" %>
                <% end %>
                <%= link_to 'Back', blogs_path, class: "btn btn-primary" %>
              </div>
            </div>
        </div>
    </article>
</section>