config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new , :create , :edit , :update]
  resources :microposts,          only: [:create, :destroy]
  resources :ads,                 only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :blogs
  resources :certificates
  resources :faqs
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  belongs_to :user
  validates :name,        presence: true
  validates :department,  presence: true
  validates :birthdate,   presence: true
  validates :graduation,  presence: true
  validates :copies,      presence: true
  validates :language,    presence: true
  validates :phone,       presence: true
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController

  before_action :logged_in_user,  only: [:create, :destroy, :new]
  before_action :correct_user,    only: [:destroy, :edit, :update, :show]
  before_action :admin_user,      only: [:destroy]

  def index
    @certificates = Certificate.all
  end

  def new
    @certificate = Certificate.new
  end

  def update
      if @certificate.update_attributes(certificate_params)
          redirect_to certificates_path
      else
          render 'edit'
      end
  end

  def show

  end

  def create
      @certificate = current_user.certificates.build(certificate_params)
      if @certificate.save
          flash[:success] = 'Application submitted!'
          redirect_to certificates_path
      else
          render 'new'
      end
  end

  def destroy
      Certificate.find(params[:id]).destroy
      flash[:success] = 'Application deleted!'
      redirect_to request.referrer || root_url
  end

  private

    def certificate_params
      params.require(:certificate).permit(:name, :department, :description,
                                          :birthdate, :graduation,
                                          :copies, :language, :phone)
    end

    def correct_user
        @certificate = current_user.certificates.find_by(id: params[:id])
        redirect_to root_url if @certificate.nil?
    end
end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_form_certificate.html.erb
<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <h3 class="panel-title pull-left"><%= yield(:form_title) %></h3>
    </div>
    <div class="modal-body">
        <%= simple_form_for @certificate do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <div class="form-group">
            <%= f.input :name, placeholder: "Your name", autofocus: true%>
        </div>

        <div class="form-group">
            <%= f.input :department, placeholder: "Your department"%>
        </div>

        <div class="form-group">
            <%= f.input :birthdate %>
        </div>

        <div class="form-group">
            <%= f.input :graduation %>
        </div>

        <div class="form-group">
            <%= f.input :copies, placeholder: "Number of copies"%>
        </div>

        <div class="form-group">
            <%= f.input :phone, placeholder: "Your phone number"%>
        </div>

        <div class="form-group">
            <%= f.input :language, collection: ["English","Japanese"] %>
        </div>

        <div class="form-group">
            <%= f.input :description, placeholder: "Describe your application",
            input_html: {rows: "5"} %>
        </div>

        <div class="form-group">
            <%= f.button :submit, class: "btn btn-primary" %>
        </div>
        <% end %>
    </div>
</div>

app/views/certificates/edit.html.erb
<% provide(:title, 'Submitted Application Forms') %>
<% provide(:form_title, 'Certificate Issuance Form') %>
<div class="container">
<!-- Page Header -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <%= yield(:title) %>
        </h1>
    </div>
</div>

<%= render 'form_certificate', certificate: @certificate %>

</div>

app/views/certificates/index.html.erb
<% provide(:title, 'Application Forms') %>
<div class="container">
    <!-- Page Header -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                <%= yield(:title) %>
            </h1>
        </div>
    </div>

    <div class="panel panel-default bootcards-summary">
        <div class="panel-heading">
            <h3 class="panel-title">New Application Forms</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <%= link_to(new_certificate_path, class: "bootcards-summary-item") do %>
                <div class="col-xs-6 col-sm-4">
                    <div class="panel panel-default text-center">
                        <h4>Certificate Issuance Form</h4>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>

    <div class="panel panel-default bootcards-summary">
        <div class="panel-heading">
            <h3 class="panel-title">Submitted Forms</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <% @certificates.each do |certificate|%>
                <%= link_to edit_certificate_path(certificate), class: "bootcards-summary-item" do %>
                <div class="col-xs-6 col-sm-4">
                    <div class="panel panel-default text-center">
                        <h4>Certificate Issuance Form</h4>
                        <small>
                            <%= certificate.created_at.strftime("%e %b %Y")%>
                            at
                            <%= certificate.created_at.strftime("%H:%M")%>
                            <% if current_user.admin? %>
                            <span style="padding-left: 55px;">
                            <%= link_to "Delete", certificate, method: :delete,
                                              data: {confirm: "Are you sure?"}%>
                            <% end %>
                          </span>
                        </small>
                    </div>
                </div>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/certificates/new.html.erb
<% provide(:title, 'New Application') %>
<% provide(:form_title, 'Certificate Issuance Form') %>
<div class="container">
<!-- Page Header -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <%= yield(:title) %>
        </h1>
    </div>
</div>

<%= render 'form_certificate' %>

</div>

app/views/certificates/show.html.erb
<% provide(:title, 'Submitted Application Forms') %>
<% provide(:form_title, 'Certificate Issuance Form') %>
<div class="container">
<!-- Page Header -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            <%= yield(:title) %>
        </h1>
    </div>
</div>

<%= render 'form_certificate', certificate: @certificate %>

</div>