config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new , :create , :edit , :update]
  resources :microposts,          only: [:create, :destroy]
  resources :ads,                 only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :blogs
  resources :certificates
  resources :faqs
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright <%= Time.now.strftime('%Y') %> &#169; AKA Group
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-custom navbar-fixed-top navbar-default">
    <div class="container">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle white" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu
                <i class="fa fa-bars"></i>
            </button>
            <%= link_to "RB", root_path, id: "logo", class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                <li><%= link_to "News Feed", root_path %></li>
                <li><%= link_to "Blogs", blogs_path %></li>
                <li><%= link_to "Forms", certificates_path %></li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <%= gravatar_for(@current_user, size: 23) %>
                        <%= @current_user.name %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Profile", current_user %></li>
                        <li><%= link_to "Find Friends", users_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li><%= link_to "Help", help_path %></li>
                        <li><%= link_to "FAQ", faqs_path %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "Log out", logout_path, method: "delete" %>
                        </li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Blogs", blogs_path %></li>
                <li><%= link_to "FAQ", faqs_path %></li>
                <li><%= link_to "Sign Up", signup_path %></li>
                <li><%= link_to "Log In", login_path %></li>
                <% end %>

            </ul>
        </div>
    </div>
    <% if logged_in? %>
    <%= render 'shared/ads_carousel' %>
    <% end %>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width" />
        <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= render 'layouts/shim' %>
    </head>

    <body>
        <br><br>
        <%= render 'layouts/header' %>

        <div class="container">

            <% flash.each do |message_type, message| %>
            <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
            <% end %>

            <%= yield %>

            <%= render 'layouts/footer' %>
        </div>
        <script>
        $('.carousel').carousel({
           interval: 5000
         })
        </script>
    </body>
</html>